---

galaxy_info:
  author: carl_backstrom
  description: Deploy common things
  license: "MIT"
  min_ansible_version: 2.3
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: ArchLinux
    versions:
    - all
  categories:
    - system

dependencies:
  - { role: geerlingguy.repo-epel, when: "ansible_os_family in ['RedHat']", become: True }
  - role: vim
  - role: tmux
  - role: kosssi.gitconfig
    git_config:
      user:
        name: Carl Bäckström
        email: genzorg@gmail.com
      core:
        editor: vim
        default: current
        excludesfile: "~/.gitignore"
    git_ignore:
      - "temp/*"
      - "prepare/*"
      - "*.sync"
      - "*.sublime-project"
      - "*.sublime-workspace"
  - role: carlba.bash_aliases
    bash_aliases:
      - { alias: 'dudefault', command: 'du -hx --max-depth=1 | sort -hr | head' }
      - { alias: 'isodate', command: 'date "+%Y-%m-%d"' }
      - { alias: 'getextip', command: 'curl http://wtfismyip.com/text' }
      - { alias: 'docker', command: 'sudo /usr/bin/docker' }
    when: ansible_os_family not in ['Darwin']
  - role: carlba.bash_aliases
    bash_aliases:
      - { alias: 'isodate', command: 'date "+%Y-%m-%d"' }
      - { alias: 'getextip', command: 'curl http://wtfismyip.com/text' }
      - { alias: 'tmuxhere', command: '' }
    when: ansible_os_family in ['Darwin']