---
- include: arch.yml
  when: ansible_os_family in ['Manjaro Linux']

- name: 'install guake'
  become: true
  package: name=guake state=present update_cache=yes
  tags: ['packages', 'guake']

#Defaults
- name: set activation key to ยง
  shell: gconftool-2 --set /apps/guake/keybindings/global/show_hide --type string "F12"
  changed_when: false
  when: false

- name: set terminal history_size to 100000
  shell: gconftool-2 --set /apps/guake/general/history_size --type int 1024
  changed_when: false
  when: false

- name: don't promt when exiting guake
  shell: gconftool-2 --set /apps/guake/general/prompt_on_quit --type bool true
  changed_when: false
  when: false

- name: don't use default font
  shell: gconftool-2 --set /apps/guake/general/use_default_font --type bool false
  changed_when: false
  when: false

- name: set default style
  shell: gconftool-2 --set /apps/guake/style/font/palette --type string "#000000000000:#cccc00000000:#4e4e9a9a0606:#c4c4a0a00000:#34346565a4a4:#757550507b7b:#060698209a9a:#d3d3d7d7cfcf:#555557575353:#efef29292929:#8a8ae2e23434:#fcfce9e94f4f:#72729f9fcfcf:#adad7f7fa8a8:#3434e2e2e2e2:#eeeeeeeeecec:#ffffffffffff:#000000000000"
  changed_when: false
  when: false

- name: set zenburn font color scheme
  shell: gconftool-2 --set /apps/guake/style/font/palette --type string "Tango"
  changed_when: false

- name: set font size
  shell: gconftool-2 --set /apps/guake/style/font/palette --type string "Monospace 10ยง"
  changed_when: false

# TODO: Should be switched to https://docs.ansible.com/ansible/gconftool2_module.html when
# Ansible 2.3 is available.
- name: set activation key to ยง
  shell: gconftool-2 --set /apps/guake/keybindings/global/show_hide --type string "section"
  changed_when: false

- name: set terminal history_size to 100000
  shell: gconftool-2 --set /apps/guake/general/history_size --type int 100000
  changed_when: false

- name: don't promt when exiting guake
  shell: gconftool-2 --set /apps/guake/general/prompt_on_quit --type bool false
  changed_when: false

- name: don't use default font
  shell: gconftool-2 --set /apps/guake/general/use_default_font --type bool false
  changed_when: false

- name: set zenburn font color scheme
  shell: gconftool-2 --set /apps/guake/style/font/palette --type string "#4D4D4D4D4D4D:#707050505050:#6060B4B48A8A:#F0F0DFDFAFAF:#505060607070:#DCDC8C8CC3C3:#8C8CD0D0D3D3:#DCDCDCDCCCCC:#707090908080:#DCDCA3A3A3A3:#C3C3BFBF9F9F:#E0E0CFCF9F9F:#9494BFBFF3F3:#ECEC9393D3D3:#9393E0E0E3E3:#FFFFFFFFFFFF:#DCDCDCDCCCCC:#3F3F3F3F3F3F"
  changed_when: false

# TODO: Make this into a block
- name: set zenburn font color scheme
  shell: gconftool-2 --set /apps/guake/style/font/palette_name --type string "Zenburn"
  changed_when: false

- name: set font size
  shell: gconftool-2 --set /apps/guake/style/font/palette --type string "Monospace 9"
  changed_when: false
