---

- import_playbook: common.yml

- import_playbook: macos.yml
  when: ansible_os_family in ['Darwin']

- hosts: all
  roles:
    - role: carlba.bash_aliases
      bash_aliases:
        - { alias: 'clipdate', command: 'date "+%Y-%m-%d" | xargs echo -n | tee >(xclip) >(xclip -sel c) > /dev/null' }
        - { alias: 'screenoff', command: 'xset dpms force off' }
        - { alias: 'mouse_sensitity_medium', command: 'xset mouse 1.9 0' }
        - { alias: 'randomize_wallpaper', command: 'feh --randomize --bg-fill ~/Dropbox/data/wallpapers' }
        - { alias: 'vi', command: 'vim' }
        - { alias: 'google-chrome-unsecure', command: 'google-chrome --disable-web-security --user-data-dir' }


    - { role: i3, when: "ansible_os_family not in ['Darwin']" }
    - role: chrome
    - role: spotify
    - { role: terminator, when: "ansible_os_family not in ['Darwin']" }
    - role: sublime
    - { role: dpi, when: "ansible_os_family not in ['Darwin']" }
    - { role: doublecmd, when: "ansible_os_family not in ['Darwin']" }
    - { role: dropbox, when: "ansible_os_family not in ['Darwin']" }
    - { role: simplenote, when: "ansible_os_family not in ['Darwin']" }
    - { role: jetbrain-toolbox, when: "ansible_os_family not in ['Darwin']" }
    - { role: rofi, when: "ansible_os_family not in ['Darwin']" }
    - { role: g810-led, when: "ansible_os_family in ['Manjaro Linux']" }
    - { role: gtk, when: "ansible_os_family in ['Manjaro Linux']" }
    - role: jeremyltn.osx-computername
      computername: "camac"
      hostname: "camac"
      localhostname: "camac"
      netbiosname: "camac"
      when: "ansible_os_family in ['Darwin']"

  tasks:
    - include: manjaro.yml
      when: ansible_os_family in ['Manjaro Linux']

    - include: ubuntu.yml
      when: ansible_distribution in ['Ubuntu']

    - name: randomize wallpaper every hour
      cron:
        name: "randomize wallpaper"
        minute: "30"
        job: "/usr/bin/feh --randomize --bg-fill /home/cada/Dropbox/data/wallpapers > /dev/null"
      when: ansible_os_family not in ['Darwin']

    - name: "make sure usb drives mounts automatically"
      become: true
      package:
        name: udiskie
        state: present
      when: ansible_os_family not in ['Darwin']

    - name: "make sure usb drives mounts automatically"
      blockinfile:
        marker: "# {mark} ANSIBLE MANAGED BLOCK (make sure usb drives mounts automatically)"
        dest: "{{ ansible_env.HOME }}/.xinitrc"
        block: "udiskie &"
        create: true
      when: ansible_os_family not in ['Darwin']

    - name: "Is R.A.T-9 mouse present"
      shell: "lsusb | grep 0738:1709"
      register: is_rat9_present
      failed_when: false
      when: ansible_os_family not in ['Darwin']

    - name: Create R.A.T config
      become: true
      template: dest=/etc/X11/xorg.conf.d/10-r.a.t.conf force=true  src=templates/r.a.t.conf.j2
      when: ansible_os_family not in ['Darwin'] and is_rat9_present.rc == 0

    - name: Create launcher for google-chrome-work
      become: true
      template:
        src: templates/google-chrome-work.j2
        dest: /usr/local/bin/google-chrome-work
        force: true
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: u+x,g+x,o+x
      when: ansible_os_family not in ['Darwin']

    - name: Create launcher for google-chrome-private
      become: true
      template:
        src: templates/google-chrome-private.j2
        dest: /usr/local/bin/google-chrome-private
        force: true
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: u+x,g+x,o+x
      when: ansible_os_family not in ['Darwin']
    - name: Configure default git diff and merge tool
      blockinfile:
        marker: "# {mark} ANSIBLE MANAGED BLOCK (Configure default git diff and merge tool)"
        dest: "{{ ansible_env.HOME }}/.gitconfig"
        block: |
          [difftool "pycharm"]
            cmd = /usr/local/bin/charm diff $LOCAL $REMOTE
            path =
            trustExitCode = true
          [mergetool "pycharm"]
            cmd = /usr/local/bin/charm merge  $LOCAL $REMOTE $BASE
            trustExitCode = true
          [merge]
              tool = pycharm
          [diff]
              tool = pycharm