---

- include: common.yml

- hosts: all
  roles:
    - role: carlba.bash_aliases
      bash_aliases:
        - { alias: 'clipdate', command: 'date "+%Y-%m-%d" | xargs echo -n | tee >(xclip) >(xclip -sel c) > /dev/null' }
        - { alias: 'screenoff', command: 'xset dpms force off' }
        - { alias: 'mouse_sensitity_medium', command: 'xset mouse 1.9 0' }
        - { alias: 'randomize_wallpaper', command: 'feh --randomize --bg-fill ~/Dropbox/data/wallpapers' }
        - { alias: 'vi', command: 'vim' }

    - role: i3
    - role: chrome
    - role: spotify
    - role: terminator
    - role: sublime
    - role: dpi
    - { role: g810-led, when: "ansible_os_family in ['Manjaro Linux']" }

  tasks:
    - include: manjaro.yml
      when: ansible_os_family in ['Manjaro Linux']

    - include: ubuntu.yml
      when: ansible_distribution in ['Ubuntu']

    - name: randomize wallpaper every hour
      cron:
        name: "randomize wallpaper"
        minute: "30"
        job: "/usr/bin/feh --randomize --bg-fill /home/cada/Dropbox/data/wallpapers > /dev/null"

    - name: "make sure usb drives mounts automatically"
      become: true
      package:
        name: udiskie
        state: present

    - name: "make sure usb drives mounts automatically"
      blockinfile:
        marker: "# {mark} ANSIBLE MANAGED BLOCK (make sure usb drives mounts automatically)"
        dest: "{{ ansible_env.HOME }}/.xinitrc"
        block: "udiskie &"
        create: true

    - name: "Is R.A.T-9 mouse present"
      shell: "lsusb | grep 0738:1709"
      register: is_rat9_present
      failed_when: false

    - name: Create R.A.T config
      become: true
      template: dest=/etc/X11/xorg.conf.d/10-r.a.t.conf force=true  src=templates/r.a.t.conf.j2
      when: is_rat9_present.rc == 0