---

- include: common.yml

- hosts: all
  roles:
    - role: carlba.bash_aliases
      bash_aliases:
        - { alias: 'clipdate', command: 'date "+%Y-%m-%d" | xargs echo -n | tee >(xclip) >(xclip -sel c) > /dev/null' }
        - { alias: 'screenoff', command: 'xset dpms force off' }
        - { alias: 'mouse_sensitity_medium', command: 'xset mouse 1.9 0' }
        - { alias: 'randomize_wallpaper', command: 'feh --randomize --bg-fill ~/Dropbox/data/wallpapers' }
        - { alias: 'vi', command: 'vim' }        

    - role: i3
    - role: chrome
    - role: spotify
    - role: terminator
    - role: sublime
    - role: dpi
    - { role: g810-led, when: "ansible_os_family in ['Manjaro Linux']" }

  tasks:
    - include: manjaro.yml
      when: ansible_os_family in ['Manjaro Linux']

    - include: ubuntu.yml
      when: ansible_distribution in ['Ubuntu']
    
    - name: randomize wallpaper every hour
      cron:
        name: "randomize wallpaper"
        minute: "30"
        job: "/usr/bin/feh --randomize --bg-fill /home/cada/Dropbox/data/wallpapers > /dev/null"

    - name: "make sure usb drives mounts automatically"
      become: true
      package:
        name: udiskie
        state: present