---
- hosts: all

  roles:
    # https://github.com/kosssi/ansible-role-gitconfig
    - role: common
    - role: kosssi.gitconfig
      git_config:
        user:
          name: Carl Bäckström
          email: genzorg@gmail.com
        core:
          editor: vim
          default: current
    - role: carlba.bash_aliases
      bash_aliases:
        - { alias: 'dudefault', command: 'du -hx --max-depth=1 | sort -hr | head' }
        - { alias: 'isodate', command: 'date "+%Y-%m-%d"' }
        - { alias: 'clipdate', command: 'date "+%Y-%m-%d" | xargs echo -n | tee >(xclip) >(xclip -sel c) > /dev/null' }
        - { alias: 'tmuxify', command: 'tmux new -s {{ ansible_env.USER}} || tmux at -t {{ ansible_env.USER }}' }
        - { alias: 'getextip', command: 'curl http://wtfismyip.com/text' }
        - { alias: 'screenoff', command: 'xset dpms force off' }
        - { alias: 'getextip', command: 'curl http://wtfismyip.com/text' }
        - { alias: 'mouse_sensitity_medium', command: 'xset mouse 1.9 0' }
        - { alias: 'vi', command: 'vim' }
        - { alias: 'randomize_wallpaper', command: 'feh --randomize --bg-fill ~/Dropbox/data/wallpapers' }
        - { alias: 'google-chrome-unsecure', command: 'google-chrome --disable-web-security --user-data-dir' }
        
    - role: vim
    - role: i3
    - role: chrome
    - role: spotify
    - role: terminator


  tasks:
    - name: enable password-less sudo for current ansible user
      become: true
      blockinfile:
        marker: "# {mark} ANSIBLE MANAGED BLOCK (enable password-less sudo)"
        dest: "/etc/sudoers"
        block: "{{ ansible_env.USER }} ALL=(ALL) ALL"

    - include: manjaro.yml
      when: ansible_os_family in ['Manjaro Linux']

    - include: ubuntu.yml
      when: ansible_distribution in ['Ubuntu']

    - name: install base
      become: true
      package: name={{item}}
      with_items:
        - git
      tags: ["packages"]

    - name: base python dependencies
      become: true
      pip:
        name: item
        executable: "{{ (ansible_os_family == 'Manjaro Linux') | ternary('pip2', 'pip') }}"
      with_items:
        - sh
        - click
        - pathlib2
        - scandir

    - name: set colors in terminal
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK (add colors in terminal)"
        block: |
          function EXT_COLOR () { echo -ne "\e[38;5;$1m"; }
          function CLOSE_COLOR () { echo -ne '\e[m'; }
          export PS1="\[`EXT_COLOR 187`\]\u@\h\[`CLOSE_COLOR`\]\[`EXT_COLOR 174`\] \w \$ \[`CLOSE_COLOR`\]"
          export LS_COLORS='di=38;5;108:fi=00:*svn-commit.tmp=31:ln=38;5;116:ex=38;5;186'
    
    - name: randomize wallpaper every hour
      cron:
        name: "randomize wallpaper"
        minute: "30"
        job: "/usr/bin/feh --randomize --bg-fill /home/cada/Dropbox/data/wallpapers > /dev/null"
