
- hosts: all
  tasks:

  - name: Speed up dock autohide
    osx_defaults:
      domain: com.apple.dock
      key: autohide-time-modifier
      type: int
      value: 0
      state: present

  - name: Speed up dock autohide
    osx_defaults:
      domain: com.apple.dock
      key: autohide-delay
      type: float
      value: 0.0
      state: present

  - name: Promt on quit
    osx_defaults:
      domain: com.googlecode.iterm2
      key: PromptOnQuit
      type: string
      value: 0
      state: present

  - name: Create KeyBindings Directory
    file:
      path: "{{ ansible_env.HOME }}/Library/KeyBindings"
      state: directory

  - name: Remap home and end to linux behaviour
    blockinfile:
      marker: "/* {mark} ANSIBLE MANAGED BLOCK (Remap home and end to linux behaviour) */"
      dest: "{{ ansible_env.HOME }}/Library/KeyBindings/DefaultKeyBinding.dict"
      create: yes
      block: |
        {
            "\UF729" = "moveToBeginningOfLine:"; /* Home */
            "\UF72B" = "moveToEndOfLine:"; /* End */
            "$\UF729" = "moveToBeginningOfLineAndModifySelection:"; /* Shift + Home */
            "$\UF72B" = "moveToEndOfLineAndModifySelection:"; /* Shift + End */
            "^\UF729" = "moveToBeginningOfDocument:"; /* Ctrl + Home */
            "^\UF72B" = "moveToEndOfDocument:"; /* Ctrl + End */
            "$^\UF729" = "moveToBeginningOfDocumentAndModifySelection:"; /* Shift + Ctrl + Home */
            "$^\UF72B" = "moveToEndOfDocumentAndModifySelection:"; /* Shift + Ctrl + End */
        }