---
# http://docs.ansible.com/ansible/galaxy.html
- src: carlba.gitconfig
  version: master
- src: carlba.bash_aliases
- src: cmprescott.chrome
- src: geerlingguy.repo-epel
- src: https://github.com/feffi/ansible-macos-computername.git
  name: feffi.macos-computername
- src: geerlingguy.pip
- src: geerlingguy.mas
- src: carlba.vim
  version: master
- src: carlba.tmux
  version: master
- src: carlba.dotfiles_minimal
  version: master
