
- hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Ensure sshpass is present (required by ansible)
      homebrew:
        name: https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb
        state: present
      when: ansible_os_family in ['Darwin']

- hosts: vagrant, servern
  gather_facts: false
  tasks:
    - name: Install Python
      become: true
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: vagrant, servern
  roles:
    - role: common
    - role: media-server
      tags: [media-server]
    - role: ghost
      tags: [ghost]
