---

- name: Get installed JetBrains Toolbox version
  shell: "jetbrains-toolbox -v"
  register: jetbrains_toolbox_version_output
  changed_when: false
  failed_when: false

- include: installation.yml
  when: jetbrains_toolbox_version_output.rc == 1 or
        jetbrains_toolbox_version not in jetbrains_toolbox_version_output.stdout