---

dependencies: 
  - role: carlba.bash_aliases
    bash_aliases: 
      - { alias: 'vi', command: 'nvim' }
      - { alias: 'vim', command: 'nvim' }

galaxy_info:
  author: carl_backstrom
  description: Deploy vim
  license: "MIT"
  min_ansible_version: 2.3
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: ArchLinux
    versions:
    - all
  categories:
    - system