---
- include_tasks: arch.yml
  when: ansible_os_family in ['Manjaro Linux']

- name: install vagrant
  package: name=vagrant state=present
  when: ansible_os_family not in ['Darwin']

- name: ensure passwordless sudo for current user
  become: true
  blockinfile:
    dest: "/etc/sudoers.d/ansible_vagrant"
    block: "{{ ansible_env.USER }} ALL=NOPASSWD: ALL"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (ensure passwordless sudo for current user)"
    create: true

- name: "install VirtualBox (MacOS)"
  homebrew_cask:
    name: virtualbox
    state: '{{ "present" if installed_state == "present" else "upgraded" }}'
  when: ansible_os_family in ['Darwin']
  tags: ["packages", "virtualbox"]

- name: "Install vagrant (MacOS)"
  block:
    - homebrew_cask: name=vagrant state=upgraded
  when: ansible_os_family in ['Darwin']
