---
- name: install Franz on MacOS
  homebrew_cask:
    name: franz
    state: present
  when: ansible_os_family in ['Darwin']

- name: Install Franz (Manjaro/Arch)
  aur: name=franz
  when: ansible_os_family in ['Manjaro Linux']

# https://github.com/meetfranz/plugins/blob/master/docs/integration.md
- name: Ensure Frans dev recipis are present in {{ franz_data_path }}
  git:
    repo: '{{ item.repo_url }}'
    dest: "{{ franz_data_path }}/recipes/dev/{{ item.name }}"
    force: true
  loop: "{{ franz_dev_recipes }}"

- name: 'Get list of directories in {{ franz_data_path }}/recipes/dev'
  find:
    paths: '{{ franz_data_path }}/recipes/dev'
    file_type: directory
  register: files_in_franz_dev_recipes

- name: Ensure only wanted Franz recipes are present
  file:
    path: '{{ item.path }}'
    state: "{{ 'absent' if (item.path | basename) not in
            (franz_dev_recipes | map(attribute='name') | list) else 'directory'}}"
  loop: '{{ files_in_franz_dev_recipes.files }}'
