# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_NAME = "ansible_dropbox"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Necessary for vagrant up to work on Ubuntu 16.10
  config.ssh.insert_key = false


  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "boxcutter/ubuntu1604-desktop"

    # Disable automatic box update checking. If you disable this, then
    # boxes will only be checked for updates when the user runs
    # `vagrant box outdated`. This is not recommended.
    # ubuntu.vm.box_check_update = false

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # ubuntu.vm.network "forwarded_port", guest: 80, host: 8080

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # ubuntu.vm.network "private_network", type: "dhcp", nic_type: "virtio"

    ubuntu.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false

      # Customize the amount of memory on the VM:
      # vb.memory = "1024"

      # Set the name of the VirtualBox instance
      vb.name = "ubuntu-" + VAGRANT_NAME
    end
    ubuntu.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
    end
  end

  config.vm.define "manjaro" do |manjaro|
    manjaro.vm.box = "rjweyers/manjaro-i3-chromium"

    # Disable automatic box update checking. If you disable this, then
    # boxes will only be checked for updates when the user runs
    # `vagrant box outdated`. This is not recommended.
    # manjaro.vm.box_check_update = false

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # manjaro.vm.network "forwarded_port", guest: 80, host: 8080

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # manjaro.vm.network "private_network", type: "dhcp", nic_type: "virtio"

    manjaro.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false

      # Customize the amount of memory on the VM:
      # vb.memory = "1024"

      # Set the name of the VirtualBox instance
      vb.name = "manjaro-" + VAGRANT_NAME
    end

    manjaro.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
    end
  end
end
