---

dependencies: []

galaxy_info:
  author: carl_backstrom
  description: Deploy resonable defaults for fonts
  license: "MIT"
  min_ansible_version: 2.3
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: ArchLinux
    versions:
    - all
  categories:
    - system