---
- include: arch.yml
  when: ansible_os_family in ['Manjaro Linux']

- include: ubuntu.yml
  when: ansible_distribution in ['Ubuntu']

- name: 'Install Spotify (MacOS)'
  homebrew_cask: name=spotify
  when: ansible_os_family in ['Darwin']
