---
# http://docs.ansible.com/ansible/apt_key_module.html
- name: Add Apt Keys (2017-01)
  become: true
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=BBEBDCB318AD50EC6865090613B00F1FD2C19886 state=present

- name: Add repository
  become: true
  apt_repository: repo='deb http://repository.spotify.com stable non-free'

- name: Install spotify
  become: true
  package: name=spotify-client update_cache=yes state=latest
