---
- name: Display all variables/facts known for a host
  debug:
    var: vars
  when: false

- include: manjaro.yml
  when: ansible_os_family in ['Manjaro Linux']

- include: ubuntu.yml
  when: ansible_distribution in ['Ubuntu']

- name: dependencies
  become: true
  pip:
    name: "{{item}}"
  with_items:
    - py3status
    - pydbus

- name: dependencies
  become: true
  package:
    name: feh

- name: "install xfce4-screenshooter"
  become: true
  package: name=xfce4-screenshooter state=present
  tags: ["packages", "i3"]

- name: get statistics for i3.config
  stat:
    path: "{{ ansible_env.HOME }}/.i3/config"
  register: i3_config_file_path_stat

- fail:
    msg: >
      Please make sure that a i3 config file {{ ansible_env.HOME }}/.i3/config it can be
      created by executing i3-config-wizard
  when: not i3_config_file_path_stat.stat.exists

- name: read i3 config extension
  local_action: shell cat {{ role_path }}/files/config
  register: i3_config_extension
  changed_when: false

- name: remove customizations (required for the modifications of base config file to work)
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.i3/config"
    block: |
      {{ i3_config_extension.stdout }}
    state: absent

- name: remove bar configurations from i3 config
  replace:
    dest: "{{ ansible_env.HOME }}/.i3/config"
    regexp: '^bar \{(.*\n){1,30}^}'
    replace: ''
    backup: no

- name: Store stuff in variable
  set_fact:
    i3_client_theme_colors: |
      # Theme colors
      # class                 border      backgr.     text        indic.      child_border
      client.focused          $i3_color8  $i3_color2  $i3_color16 $i3_color12
      client.focused_inactive $i3_color9  $i3_color9  $i3_color16 $i3_color10
      client.unfocused        $i3_color9  $i3_color9  $i3_color16 $i3_color10
      client.urgent           $i3_color13 $i3_color12 $i3_color16 $i3_color14
      client.placeholder      $i3_color15 $i3_color17 $i3_color16 $i3_color15 $i3_color17

      client.background       $i3_background

- name: remove color scheme configuration
  replace:
    dest: "{{ ansible_env.HOME }}/.i3/config"
    regexp: '^# Theme colors(\n|.)*client\.background.*$'
    replace: "{{ i3_client_theme_colors }}"
    backup: no

- name: set client theme colors
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK (set client theme colors)"
    dest: "{{ ansible_env.HOME }}/.i3/config"
    block: "{{ i3_client_theme_colors }}"
    create: yes
  when: false

- name: Set proper font for i3
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.i3/config"
    regexp: '^font.*$'
    line: 'font pango:Cousine, FontAwesome 9'

- name: Set inner gaps to 0
  replace:
    path: "{{ ansible_env.HOME }}/.i3/config"
    regexp: '^gaps inner.*$'
    replace: 'gaps inner 0'

- name: Set outer gaps to 0
  replace:
    path: "{{ ansible_env.HOME }}/.i3/config"
    regexp: '^gaps outer.*$'
    replace: 'gaps outer 0'

- name: Replace default terminal with terminator
  replace:
    path: "{{ ansible_env.HOME }}/.i3/config"
    regexp: '^bindsym \$mod\+Return exec terminal$'
    replace: 'bindsym $mod+Return exec terminator --command "tmuxify"'

- name: Replace default dmenu with rofi
  replace:
    path: "{{ ansible_env.HOME }}/.i3/config"
    regexp: '^bindsym \$mod\+d exec --no-startup-id dmenu_recency$'
    replace: 'bindsym $mod+d exec "rofi -combi-modi window,drun,run,Sublime:rofi_sublime_projects,PyCharm:rofi_pycharm_projects -show combi -modi combi"'

- name:  Make sure windows has borders
  replace:
    path: "{{ ansible_env.HOME }}/.i3/config"
    regexp: '^new_window pixel 1'
    replace: 'new_window normal'

- name: Prevent compton from autostarting
  lineinfile:
    path: "{{ ansible_env.HOME }}/.i3/config"
    line: 'exec --no-startup-id nitrogen --restore; sleep 1; compton -b'
    state: absent

- name: Prevent compton from autostarting
  lineinfile:
    path: "{{ ansible_env.HOME }}/.i3/config"
    line: 'bindsym $mod+t exec --no-startup-id pkill compton'
    state: absent

- name: Prevent compton from autostarting
  lineinfile:
    path: "{{ ansible_env.HOME }}/.i3/config"
    line: 'bindsym $mod+Ctrl+t exec --no-startup-id compton -b'
    state: absent

- name: Disable mod+space shortcut
  replace:
    path: "{{ ansible_env.HOME }}/.i3/config"
    regexp: '^(bindsym \$mod\+space focus mode_toggle)'
    replace: '# \1'

- name: add i3 config
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.i3/config"
    block: |
      {{ i3_config_extension.stdout }}

- name: Run gnome-settings-daemon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK (Run gnome-settings-daemon)"
    dest: "{{ ansible_env.HOME }}/.i3/config"
    block: |
      exec --no-startup-id gnome-settings-daemon
  when: ansible_distribution in ['Ubuntu']

- name: copy i3status.conf
  copy:
    force: yes
    src: "{{ role_path }}/files/i3status.conf"
    dest: "{{ ansible_env.HOME }}/.i3/i3status.conf"

- name: copy i3status_lite.conf
  copy:
    force: yes
    src: "{{ role_path }}/files/i3status_lite.conf"
    dest: "{{ ansible_env.HOME }}/.i3/i3status_lite.conf"

# The entry point provided by the package installer is much slower then just running the file
# TODO: Figure out to use the installed package instead of just downloading the script.
- name: Download quickswitch.py
  become: true
  get_url:
    url: https://raw.githubusercontent.com/carlba/quickswitch-for-i3/master/quickswitch.py
    dest: /usr/bin/quickswitch
    force: yes
