---

- name: "install i3"
  become: true
  package: name=i3-gaps state=present
  tags: ["packages", "i3"]

- name: dependencies
  aur:
    name: ttf-font-awesome
    tool: pacaur

- name: dependencies
  become: true
  package:
    name: python2-gobject
  when: ansible_os_family in ['Manjaro Linux']

- name: deploy skel default i3 config
  copy:
    src: /etc/skel/.i3/config
    dest: "{{ ansible_env.HOME }}/.i3/config"