---

galaxy_info:
  author: genzorg@gmail.com (Carl Bäckström)
  description: Configures a server to be a Mysql Client
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - database:mysql
