---
# tasks file for autorandr

- name: "Is Logitech G810 present"
  shell: "lsusb | grep 046d:c337"
  register: is_logitech_g810_present
  failed_when: false

- include: installation.yml
  when: is_logitech_g810_present.rc == 0