---
- block: 
  - name: "set dpi to {{ expected_dpi }}"
    blockinfile:
      marker: "# {mark} ANSIBLE MANAGED BLOCK (set dpi)"
      dest: "{{ ansible_env.HOME }}/.Xresources"
      block: "Xft.dpi:{{ expected_dpi }}"
      create: yes

  - name: "set dpi to {{ expected_dpi }} (permanently)"
    blockinfile:
      marker: "# {mark} ANSIBLE MANAGED BLOCK (set dpi)"
      dest: "{{ ansible_env.HOME }}/.xprofile"
      block: "xrandr --dpi {{ expected_dpi }}"
      create: yes

  - name: check dpi
    shell: xdpyinfo | grep dots | cut -d' ' -f 7
    register: dpi_command_result
    changed_when: false

  - name: set dpi variable
    set_fact:
      current_dpi: "{{ dpi_command_result.stdout.split('x') | first() }}"

  - name: "set dpi to {{ expected_dpi }} (temporarily)"
    shell: "xrandr --dpi {{ expected_dpi }}"
    when: current_dpi != expected_dpi
    failed_when: false # This will always fail if as display is not availible