---
- block:
  - name: set expected dpi variable
    set_fact:
      expected_dpi: "102"
  
  - name: "set dpi to {{ expected_dpi }}"
    blockinfile:
      marker: "# {mark} ANSIBLE MANAGED BLOCK (set dpi to 98)"
      dest: "{{ ansible_env.HOME }}/.Xresources"
      block: "Xft.dpi:{{ expected_dpi }}"

  - name: set dpi to 98 (permanently)
    blockinfile:
      marker: "# {mark} ANSIBLE MANAGED BLOCK (set dpi to 98)"
      dest: "{{ ansible_env.HOME }}/.xprofile"
      block: "xrandr --dpi {{ expected_dpi }}"

  - name: check dpi
    shell: xdpyinfo | grep dots | cut -d' ' -f 7
    register: dpi_command_result
    changed_when: false

  - name: set dpi variable
    set_fact:
      dpi: "{{ dpi_command_result.stdout.split('x') | first() }}"

  - name: "set dpi to {{ expected_dpi }} (temporarily)"
    shell: "xrandr --dpi {{ expected_dpi }}"
    when: dpi != "{{ expected_dpi }}"