---
- name: get installed tmux version
  shell: "tmux -V"
  register: tmux_version_output
  changed_when: false
  failed_when: false

- include: installation.yml
  when: ansible_os_family in ['Manjaro Linux'] and tmux_version_output.stdout != "tmux 2.5"

- include: installation.yml
  when:  ansible_distribution in ['Ubuntu'] and tmux_version_output.stdout != "tmux 2.1"

- include: installation.yml
  when:  ansible_os_family in ['RedHat'] and tmux_version_output.stdout != "tmux 2.5"

- include: configuration.yml