---
- name: get installed tmux version
  shell: "tmux -V"
  register: tmux_version_output
  changed_when: false

- include: installation.yml
  when: tmux_version_output.stdout != "tmux 2.5"

- name: make sure 256 colors is used in tmux
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (make sure 256 colors is used in tmux)"
    content: export TERM=xterm-256color
    state: present

# https://gist.github.com/limingjie/4975c36d13d0927613e6
- name: make sure 256 colors is used in tmux
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (make sure 256 colors is used in tmux)"
    content: set -g default-terminal "screen-256color"
    state: present