---

- name: make sure sublime is not running
  shell: killall "sublime_text"
  when: ansible_os_family not in ['Darwin']

- name: make sure sublime is not running
  shell: pkill "Sublime Text"
  when: ansible_os_family in ['Darwin']
  ignore_errors: true

- include: arch.yml
  when: ansible_os_family in ['Manjaro Linux']

- include: ubuntu.yml
  when: ansible_distribution in ['Ubuntu']

- name: install sublime on MacOS
  homebrew_cask:
    name: sublime-text
    state: upgraded
  when: ansible_os_family in ['Darwin']

- set_fact:
     sublime_user_path: "{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 3/Packages/User"
     sublime_installed_packages_path: "{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 3/Installed Packages"
  when: ansible_os_family in ['Darwin']

- name: install dependencies
  become: true
  pip: name=ansible-lint executable=pip2

- name: get stat for sublime user path
  become: false
  stat:
    path: "{{ sublime_user_path }}"
  register: sublime_user_path_stat

- file:
    path: "{{ sublime_user_path }}"
    recurse: true
    state: directory

- file:
    path: "{{ sublime_installed_packages_path }}"
    recurse: true
    state: directory

- name: Download Sublime Package Control
  get_url:
    url: https://packagecontrol.io/Package%20Control.sublime-package
    dest: "{{ sublime_installed_packages_path }}/Package Control.sublime-package"

- template:
    src: "templates/Package Control.sublime-settings.j2"
    dest: "{{ sublime_user_path }}/Package Control.sublime-settings"
    force: false

- template:
    src: "templates/SyncSettings.sublime-settings.j2"
    dest: "{{ sublime_user_path }}/SyncSettings.sublime-settings"
