- name: Install Python pip (python3)
  become: true
  shell: "curl https://bootstrap.pypa.io/get-pip.py | python3"


# TODO: The monitor config should be based on hostname not dist

- name: Create monitor config
  become: true
  template:
    src: "templates/10-monitor.conf.j2"
    dest: "/etc/X11/xorg.conf.d/10-monitor.conf"