---
# http://docs.python-guide.org/en/latest/starting/install/osx/
- name: Install Python (MacOS)
  package: name={{item}}
  with_items:
    - python
    - python2
  tags: ["packages"]
  when: ansible_os_family in ['Darwin']

- name: link python2
  shell: brew link --force python2

- name: make sure .bashrc is sourced
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (make sure .bashrc is sourced)"
    create: true
    insertbefore: BOF
    block: |
      if [ -f ~/.bashrc ]; then
          . ~/.bashrc
      fi

# http://davidalger.com/development/bash-completion-on-os-x-with-brew/
- name: make sure bash completion is sourced
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (make sure bash completion is sourced)"
    create: true
    block: |
      if [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
      fi