---
- name: Enable sudo for current ansible user (Done first so that it doesn't interfere with other changes to sudoers list)
  become: true
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK (enable sudo for {{ ansible_env.USER }})"
    dest: "/etc/sudoers"
    block: "{{ ansible_env.USER }} ALL=(ALL) ALL"
  when: ansible_os_family in ['Darwin']

- name: Enable password-less docker usage for current ansible user
  become: true
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK (enable password-less docker usage for {{ansible_env.USER}})"
    dest: "/etc/sudoers"
    block: "{{ ansible_env.USER }} ALL=(root) NOPASSWD: /usr/bin/docker"
  when: ansible_os_family not in ['Darwin']

- include: arch.yml
  when: ansible_os_family in ['Manjaro Linux']

- include: ubuntu.yml
  when: ansible_distribution in ['Ubuntu']

- include: macos.yml
  when: ansible_os_family in ['Darwin']

- name: install base
  become: "{{ (ansible_os_family in ['Darwin']) | ternary('false', 'true') }}"
  package: name={{item}}
  with_items:
    - git
    - jq
    - htop
    - wget
    - bash-completion
  tags: ["packages"]

# TODO: Make man dependency installable in manjaro.
# For some reason the play failes on this on manjaro
- name: install man
  become: "{{ (ansible_os_family in ['Darwin']) | ternary('false', 'true') }}"
  package: name={{item}}
  with_items:
    - man
  tags: ["packages"]
  when: ansible_os_family in ['Manjaro Linux']

- name: Install Python pip (python2)
  become: true
  shell: "curl https://bootstrap.pypa.io/get-pip.py | python2"
  when: ansible_os_family not in ['Darwin']

- name: base python dependencies
  become: "{{ (ansible_os_family in ['Darwin']) | ternary('false', 'true') }}"
  pip:
    name: item
    executable: "{{ pip_executable }}"
  with_items:
    - sh
    - click
    - pathlib2
    - scandir
  when: ansible_os_family not in ['RedHat']

# https://sanctum.geek.nz/arabesque/better-bash-history/
- name: better bash history
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK (better bash history)"
    block: |
      HISTFILESIZE=1000000
      HISTSIZE=1000000
      HISTCONTROL=ignoreboth
      HISTTIMEFORMAT='%Y-%m-%dT%T '
      shopt -s cmdhist
      shopt -s histappend

- name: set colors in terminal
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK (add colors in terminal)"
    block: |
      function EXT_COLOR () { echo -ne "\e[38;5;$1m"; }
      function CLOSE_COLOR () { echo -ne '\e[m'; }
      export PS1="\[`EXT_COLOR 187`\]\u@\h\[`CLOSE_COLOR`\]\[`EXT_COLOR 174`\] \w \$ \[`CLOSE_COLOR`\]"
      export LS_COLORS='di=38;5;108:fi=00:*svn-commit.tmp=31:ln=38;5;116:ex=38;5;186'

- name: configure US and SE keyboard layout and toggle with CAPSLOCK
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.profile"
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK (configure US and SE keyboard layout and toggle with CAPSLOCK)"
    block: |
      setxkbmap -option grp:switch,grp:caps_toggle us,se