---

- name: Get installed neovim version
  shell: "nvim --version | head -n 1"
  register: neovim_version_output
  changed_when: false

- include: arch.yml
  when: ansible_os_family in ['Manjaro Linux'] and neovim_version_output.stdout != "NVIM v0.2.0"

- include: ubuntu.yml
  when: ansible_distribution in ['Ubuntu'] and neovim_version_output.stdout != "NVIM v0.2.0"

- include: rhel.yml
  when: ansible_os_family in ['RedHat'] and not "NVIM v0.2.1" in neovim_version_output.stdout

- name: Install neovim for Ubuntu and Arch/Manjaro
  become: true
  package: name=neovim state=present
  tags: ["packages", "vim"]
  when: ansible_distribution in ['Ubuntu'] or ansible_os_family in ['Manjaro Linux'] and
        neovim_version_output.stdout != "NVIM v0.2.0"

# TODO: Leaving this here to make sure the repo is cleaned up. Should be removed at later time
- name: Remove repository (and clean up left-over metadata)
  become: true
  file:
    path: /etc/yum.repos.d/dperson-neovim-epel-7.repo
    state: absent

- name: Install neovim Python library
  become: true
  pip:
    name: neovim

- name: Make sure nvim config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    recurse: true
    state: directory

# TODO: Convert to get_url statement
- name: Install vim-bootstrap from http://vim-bootstrap.com
  shell: "curl 'http://vim-bootstrap.com/generate.vim' --data 'langs=javascript&langs=php&langs=html&langs=ruby&langs=python&editor=nvim' > {{ ansible_env.HOME }}/.config/nvim/init.vim"
  tags: ["packages", "vim"]

# TODO: Detect if successful?
- name: Update vim bundles
  shell: nvim +PlugInstall +qall --headless

# nocompatible prevents home and end buttons from inserting H and F characters
- name: Apply customized vim settings
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.config/nvim/local_init.vim"
    create: true
    marker: ' " {mark} ANSIBLE MANAGED BLOCK'
    block: |
      colorscheme zenburn
      set nocompatible
      let g:airline_theme = 'lucius'
      autocmd FileType python setlocal colorcolumn=99
      set guicursor=

- name: Add custom plugins
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.config/nvim/local_bundles.vim"
    create: true
    marker: ' " {mark} ANSIBLE MANAGED BLOCK'
    block: |
      Plug 'vim-scripts/Zenburn'

# TODO: Detect if successful?
- name: Update vim bundles
  shell: nvim +PlugInstall +qall --headless


