

- name: install dependencies for building neovim
  become: true
  yum: name={{item}}
  with_items:
      - gcc-c++
      - unzip
      - cmake
      - libtool

- name: Create temp directory
  tempfile:
    state: directory
    suffix: neovim_install
  register: neovim_tempdir

- name: Checkout Neovim repo
  git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ neovim_tempdir.path }}"

- name: prepare neovim for installation
  make:
    chdir: "{{ neovim_tempdir.path }}"

- name: Install neovim
  become: yes
  make:
    chdir: "{{ neovim_tempdir.path }}"
    target: install
