---

- name: "Install Neovim PPA"
  become: true
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'
    update_cache: yes

- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  apt:
    update_cache: yes