---
- name: Ensure fontconfig directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/fontconfig"
    state: directory

- name: Add default font settings
  template:
    src: font.config.j2
    dest: "{{ ansible_env.HOME }}/.config/fontconfig/font.config"